spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#Active profile
  profiles:
    active: local

#Email-agent
  mail:
    host: ${MAIL_HOST:smtp.yandex.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:email_username}
    password: ${MAIL_PASSWORD:email_password}
    email_alias: ${EMAIL_ALIAS:email_alias}
    protocol: ${MAIL_PROTOCOL:smtps}

#DB settings
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME:username}
    password: ${PG_PASSWORD:password}
    url: ${PG_URL:jdbc:postgresql://localhost:5432/mambet_pages}
  jpa:
    hibernate :
      ddl-auto : none
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${SCHEMA_NAME:mambet_pages}

#Swagger
springdoc:
  swagger-ui:
    path: api