spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: local
  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    email_alias:
    protocol: smtps
springdoc:
  swagger-ui:
    path: api